name: Node.js Google App Engine CI

on:
  push:
    branches: [ "main" ]

jobs:
  build_deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: GCP Authentication
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GAE_LUMBA_FE_CREDENTIALS }}'

    - name: Google App Engine Deploy
      id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v2'
